### ISSUE TITLE
Light theme doesn't work for Dialect and Flatseal

### ISSUE THREAD

**Issue by Microwave-WYB** [lassekongo83/adw-gtk3#116]
![image](https://user-images.githubusercontent.com/68882116/167932146-e5958b43-cd5f-437d-8714-92e7f25e54be.png)

I reinstalled the theme and the problem remained.
There's no issue with the dark variant and I haven't found more applications with the same issue.

**Comment by daudix-UFO** [comment]
That Because it's flatpaks, & it uses current gnome gtk variant, gnome automaticlu don't change it to dark, so, I made it with extension called "Night Theme Switcher" , here, in commands section put this:

Light : `sleep 0.7 && gsettings set org.gnome.desktop.interface gtk-theme adw-gtk3`

Dark : `sleep 0.7 && gsettings set org.gnome.desktop.interface gtk-theme adw-gtk3-dark`

That will change theme for all your apps, & flatpaks, Hope this will help ;)
![Снимок экрана от 2022-05-11 23-49-38](https://user-images.githubusercontent.com/77155297/167945206-70c2c8e2-2255-40f9-9b7f-d2bad85bd970.png)

**Comment by Microwave-WYB** [comment]
> That Because it's flatpaks, & it uses current gnome gtk variant, gnome does not automaticly change it to dark, so, I made it with extension called "Night Theme Switcher" , here, in commands section put this:
> 
> Light : `sleep 0.7 && gsettings set org.gnome.desktop.interface gtk-theme adw-gtk3`
> 
> Dark : `sleep 0.7 && gsettings set org.gnome.desktop.interface gtk-theme adw-gtk3-dark`
> 
> That will change theme for all your apps, & flatpaks, Hope this will help ;) ![Screenshot from 2022-05-11 23-53-15](https://user-images.githubusercontent.com/77155297/167946036-ea7bb8ea-dccf-4f04-84ac-ab7676347b72.png) ![Screenshot from 2022-05-11 23-52-55](https://user-images.githubusercontent.com/77155297/167946094-70c66f46-c84a-46b9-a30c-b9cae91dc341.png) ![Screenshot from 2022-05-11 23-52-52](https://user-images.githubusercontent.com/77155297/167946137-774a43da-4ace-4620-9acc-5eb81d89ca6e.png)

This is not my case. I am using night theme switcher plugin. The problem is about the light theme variant. When manually set theme variant to dark, the GTK3 applications looks fine. But when set to light, some flatpak applications looks strange. 
![image](https://user-images.githubusercontent.com/68882116/167947570-6e44986e-4355-4fa7-857c-d422e98a8874.png)
![image](https://user-images.githubusercontent.com/68882116/167947600-77800a85-8875-4664-b5c5-d53598835a09.png)

**Comment by lassekongo83** [comment]
Did you install the light flatpak theme?

**Comment by Microwave-WYB** [comment]
> Did you install the light flatpak theme? (Installed with sudo or not?)

That solves everything, thank you.
