### ISSUE TITLE
New Google Chrome Tab UI

### ISSUE THREAD

**Issue by seanleavy** [lassekongo83/adw-gtk3#247]
### Prerequisites

- [X] I performed a [cursory search of the issue tracker](https://github.com/lassekongo83/adw-gtk3/issues?q=is%3Aissue) to avoid opening a duplicate issue.

### Checklist to make sure the issue is not on your end

- [X] I have made sure that I do not have multiple versions of the theme installed. Only one version should be installed in either `~/.local/share/themes` or `/usr/share/themes` or `~/.themes`
- [X] The file `~/.config/gtk-3.0/gtk.css` does not exist. (If it does, backup and remove it.)
- [X] I have logged out and in again.
- [X] Dark theme only. I have enabled adw-gtk3-dark in `gnome-tweaks` AND set the appearance to dark in `gnome-control-center`
- [X] The flatpak theme is installed `org.gtk.Gtk3theme.adw-gtk3` and `org.gtk.Gtk3theme.adw-gtk3-dark`
- [X] The app I'm having an issue with is an actual GTK3 app and is not coded using another toolkit like GTK2, GTK4, QT, etc.
- [X] I have created a new user profile without any modifications except adw-gtk3.

### Description

Google Chrome is changing the style of the tabs. They will now have a light background colour & will clash with the white Libadwaita look. This screenshot below is from Google Chrome version 121.0.6156.3 (Official Build) dev (64-bit). The change has not hit stable yet thankfully.

Default Adwaita :
![Screenshot from 2023-12-06 13-31-59](https://github.com/lassekongo83/adw-gtk3/assets/2906363/2653bf02-1b75-497b-b621-e3f3ae5c1b2b)

Adw-gtk:

![Screenshot from 2023-12-06 13-36-47](https://github.com/lassekongo83/adw-gtk3/assets/2906363/c2f2efb3-95ea-4969-99a2-3528723777cc)

### OS and version [e.g Fedora 37]

39

### Adw-gtk3 version. Also specify your installation source. [e.g tar.xz, AUR, git main branch]

5.1

### GNOME version

45.2

### Application name and version (If the issue is with an app.)

Google Chrome 121

**Comment by astrocaat** [comment]
@lassekongo83 I started seeing the grey titlebar in some apps that I use and I came here to see the reason of the change. Is it really necessary to revert the headerbar bg just for the consistency of one application? I really liked the white color because it was consistent with libadwaita and all the other apps I use, now it looks very off :(
Those who use Chrome can use built-in themes to customize the look according to their preferences, while other apps can't just do that...

**Comment by lassekongo83** [comment]
@astrocaat White is really not a good color for a headerbar unless it flows into the rest of the content which GTK3 is very limited with. It can only be done with a few selected apps like geary and gnome-tweaks.

It's still possible to get a white headerbar though. Edit `~/.config/gtk-3.0/gtk.css` and add `@define-color headerbar_bg_color #ffffff;`

**Comment by astrocaat** [comment]
@lassekongo83 thank you. Your hack works but when the theme automatically changes to dark the headerbar stays white. Do you have any solution for this?

**Comment by lassekongo83** [comment]
The `~/.config/gtk-3.0/gtk.css` file can't tell if the theme has changed to dark or not.

**Comment by LSeelig** [comment]
@astrocaat I made a soft [fork](https://github.com/LSeelig/adw-gtk3-white-headers) to achieve this without hacking the gtk.css because, yeah, it has trouble with my dark/light theme switch. If you have any programs that have problems with white headers, you can launch them with an environmental variable to specify the original adw-gtk3.
