### ISSUE TITLE
eog titlebar issue

### ISSUE THREAD

**Issue by Alexmelman88** [lassekongo83/adw-gtk3#97]
![Снимок экрана от 2022-04-27 02-42-57](https://user-images.githubusercontent.com/99257010/165492037-b26640d8-4520-4dae-8e92-b9553bf7f839.png)

**Comment by diego-pvlk** [comment]
This is fixed with the latest commit, it was also affecting nautilus search bar.

But the search icon is not properly aligned (nautilus 42), same for FSearch app, probably others as well: 
![](https://user-images.githubusercontent.com/25941156/165553950-17ea2117-3a5e-481d-b347-5493083092e5.png)
![](https://user-images.githubusercontent.com/25941156/165553953-9c42cece-0303-400a-9f01-da3ad23172cb.png)
